RDM-10044 - Case event publish column
hmcts/befta-fw pull request #119
Opened 2020-11-18 16:25 UTC by smathangi

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDM-10044

### Change description ###

New Publish Column for Case Events

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2020-11-18 17:21 UTC, VamshiRudrabhatlaHMCTS approved these changes

2020-11-19 15:50 UTC, mattnayler requested changes
If there are updates to anuy of the main BEFTA definition files then [the corresponding JSON](https://github.com/hmcts/befta-fw/tree/master/src/main/resources/uk/gov/hmcts/befta/dse/ccd/definitions/valid) should be regenerated.  (hopefully there is documentation and/or a scripted command on how to do this by now: otherwise check-in with a QA or @sullivangareth)

2020-11-19 15:58 UTC, smathangi commented
> If there are updates to anuy of the main BEFTA definition files then [the corresponding JSON](https://github.com/hmcts/befta-fw/tree/master/src/main/resources/uk/gov/hmcts/befta/dse/ccd/definitions/valid) should be regenerated. (hopefully there is documentation and/or a scripted command on how to do this by now: otherwise check-in with a QA or @sullivangareth)

So every time we update spreadsheet we have to update jsons as well :( ?

2020-11-23 16:16 UTC, sullivangareth approved these changes

2020-11-23 16:20 UTC, merged