GA-3 Add a new Tab AccessTypeRoles in the DefinitionStore
hmcts/befta-fw pull request #199
Opened 2023-12-01 13:25 UTC by patelila

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-01-04 09:47 UTC, sanjayparekh-hmcts requested changes

2024-01-04 09:47 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/befta/dse/ccd/definition/converter/JsonTransformer.java
> +            "NoticeOfChangeConfig", "ChallengeQuestion", "RoleToAccessProfiles", "SearchParty", "SearchCriteria","AccessTypeRoles");
sorry to be super pendantic - can you add a space after the comma here to be consistent!

2024-01-10 17:15 UTC, sanjayparekh-hmcts approved these changes

2024-01-11 09:10 UTC, RebeccaBaker approved these changes

2024-02-21 10:23 UTC, helenbirdhmcts approved these changes

2024-02-21 10:51 UTC, merged